name: Clang Format

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Format
      uses: DoozyX/clang-format-lint-action@v0.11
      with:
        source: './lib ./include'       
        clangFormatVersion: 11
        inplace: True
    - name: Commit
      uses: EndBug/add-and-commit@v4
      with:
        author_name: reSHARMA
        author_email: reshabhsh@gmail.com
        message: 'Auto format changes'
